# Generated by Django 4.0.4 on 2022-06-03 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=100, null=True)),
                ('surname_text', models.CharField(max_length=100, null=True)),
                ('phonenumber_number', models.CharField(max_length=100, null=True)),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonebook.phonebook')),
            ],
        ),
    ]
